### ISSUE TITLE
Filenames with dots (in addition to the extension) are cut off in tab title

### ISSUE THREAD

**Issue by stygianguest** [Acly/hdrv#13]
For reasons related to gnu make I have many pfm files with dots in the name which is cut off by
Consequently, when I open two files asdf.a.pfm and asdf.b.pfm I cannot distinguis them in the tabs because both are named 'asdf'.

**Comment by Acly** [comment]
Exchanged use of `QFileInfo::baseName` with `QFileInfo::completeBaseName`, that should show everything up to the _last_ dot.
