### ISSUE TITLE
Some HDR formats not loaded

### ISSUE THREAD

**Issue by Renderking** [Acly/hdrv#14]
Hi!

Some HDRIs are not loaded.
Sample file attached.

![hdrviewer-problemhdr](https://cloud.githubusercontent.com/assets/23197696/24039398/4d5d2244-0b05-11e7-9706-e997955ffb2d.png)

Greetings,
Jan

**Comment by Acly** [comment]
Sample file attached where?

Is it a .hdr exported by photoshop by any chance? I recall these not loading in the past, photoshop doesn't export proper .hdrs (according to radiance spec) but does its own thing.

**Comment by Renderking** [comment]
Hi!

The header says it was created with Blender.
I actually tried to attach as ZIP, but somehow GitHub does not like it.
I give it to you tomorrow. ;-)
