### ISSUE TITLE
Still can't load HDR images

### ISSUE THREAD

**Issue by Renderking** [Acly/hdrv#15]
I tried again to read HDR images and the 2 attached images give the errors in the screen shot.
[balcony_256p.zip](https://github.com/Acly/hdrv/files/1501585/balcony_256p.zip)
[sky128.zip](https://github.com/Acly/hdrv/files/1501587/sky128.zip)
![2017-11-24 13_07_21-sky128 - hdrv 0 4](https://user-images.githubusercontent.com/23197696/33210014-c81b673c-d118-11e7-8fcf-b8164b00c831.png)
![2017-11-24 13_08_31-balcony_256p - hdrv 0 4](https://user-images.githubusercontent.com/23197696/33210015-c832d0b6-d118-11e7-989b-da0e9e761d2c.png)

**Comment by Acly** [comment]
balcony_256p should load with master (it does for me), though not with 0.4 release.
sky128 seems like it doesn't use run-length-encoded scanlines. I'm going to just assume it stores the data uncompressed, looks like the first part of the image resembles some sort of sky then at least. The second half of the image is all zeroes which looks rather broken though.

**Comment by Acly** [comment]
Try [Release 0.5](https://github.com/Acly/hdrv/releases/tag/v0.5)
